name: publish

on: push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Install PNPM
        uses: pnpm/action-setup@v1.2.1
        with:
          version: "5.18.7"

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Push to registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
